---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
library("ggplot2")
library("janitor")
library("tidyverse")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!
```{r}
heartrate<-read.csv("data/heartrate.csv")
```


1. Make a plot that compares the heartrate of patients for drug a.
```{r}
heartrate%>%
  ggplot(aes(patient, a, fill = patient))+
  geom_col()+
  labs(x="Patient", y="Heartrate for Drug A")
```


2. Make a plot that compares heartrate (as a range) for each drug.
```{r}
heartrate%>%
  pivot_longer(cols=-"patient", names_to = "drug", values_to = "heartrate")%>%
  ggplot(aes(drug, heartrate, fill = drug))+
  geom_boxplot()+
  labs(title = "Heartrate Ranges For Each Drug", x="Drug", y="Heartrate")
```

